# 测试项目
[project]
name = 'Dz_like_bofa_admin'

# 测试报告
[report]
title = "power_bank接口自动化测试报告"
tester_name = 'Rookie'
# jenkins allure (固定地址，总是指向最新报告)
jenkins_url = 'http://47.76.165.189:8080/job/Dz_Like_bofa_admin/allure/'

# mysql 数据库（可选，如不需要请留空或删除配置）
[mysql]
host = ''
port = 6306
user = ''
password = ''
database = ''
charset = 'utf8mb4'

# redis 数据库（可选，如不需要请留空或删除配置）
[redis]
host = ''
port = 6379
password = ''
database = 0
timeout = 10

# 邮件
[email]
host = ''
port = 465
user = ''
password = ''
receiver = ''  # if more, use: [str]
ssl = true
send = false

# 钉钉
[dingding]
webhook = ''
proxies.http = ''
proxies.https = ''
send = false

# 飞书
[feishu]
webhook = ''
proxies.http = ''
proxies.https = ''
send = false

# 企业微信
[wechat]
webhook = ''
proxies.http = ''
proxies.https = ''
send = false

# Telegram
[telegram]
bot_token = '6968270418:AAGlX7tNpfnIuueB2hAssZWzwuNCMjR6ryE'
chat_id = '-4781359846'
proxies.http = ''
proxies.https = ''
send = true

# 请求发送
[request]
global_env = ''
timeout = 10
verify = false
redirects = true
proxies.http = ''
proxies.https = ''
retry = 3

# 加密配置
[encryption]
enabled = false
key = "your-32-byte-secure-aes-key-1234"
